### ISSUE TITLE
☂️👣 Breaking Changes for 0.4.0

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse-ci#119]
A comprehensive list of changes that are being saved for a breaking 0.4.0 version.

## Last 0.3.x release

- [x] CLI healthcheck for hitting incompatible server
- [x] visual cue for version change in timeline
- [x] visual cue in build view for version change
- [x] reset project token wizard
- [x] fix issue with dashboard choosing bad URL by default

## Must Have

- [x] change default minScore to 0.9 https://github.com/GoogleChrome/lighthouse-ci/issues/295#issuecomment-622535215
- [x] move dom-size audit out of recommended preset
- [x] remove old dashboard design
- [x] upgrade to lighthouse 6.0 🎉 
  - [x] transferSize of budgets
  - [x] graphs for LCP & TBT
  - [x] support subRows
  - [x] support source-location details
  - [x] update presets with 6.0 audits
  - [x] upgrade the actual collection to 6.0
  - [ ] ???
- [x] replace `_average` statistics with `_median`
- [x] require project token for all created builds
- [x] recursive search and limit 5 with static-dist-dir by default (ref #95)

## Docs to update

- [x] 0.3.x references
- [x] timing budgets to add

## Not really breaking, for next release

- support a "root token" requirement to create new projects https://github.com/GoogleChrome/lighthouse-ci/issues/323
- PSI runner https://github.com/GoogleChrome/lighthouse-ci/issues/251
- PSI cron job support in server projects

## Punt

Churn without a ton of benefit.

- [ ] move upload options into objects nested by target type (for clarity and to resolve fact that wizard and upload have overlapping keys https://github.com/GoogleChrome/lighthouse-ci/pull/200#discussion_r372467370)
