### ISSUE TITLE
MVP Burndown

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse-ci#9]
Burndown list created for items outstanding as of 2019-10-01 or later.

### UI
- [x] PWA Gauge (c881617a6e44377d1286d654ad4d895df4222ea7)
- [x] numeric audit tweaks for overflow text (6eaf47d97f05942916af56cb06d5e2c2d59af16c)
- [x] ellipsis overflow text on audit name (6eaf47d97f05942916af56cb06d5e2c2d59af16c)
- [x] use SVG for the border triangle icon (48a30efad9beb7768cdcaab74282683c1eafe1b8)
- [x] multiple URL graphs on project dashboard (e24d46f6416e0dba6bf47c043284674fefa2429e)
- [x] support node details type in table (f6555997)
- [x] markdown description support (2e9a282f)
- [x] pass/fail/icon indicator in audit detail view (2e9a282f)
- [x] hide gauges when detail is expanded (ccf61b6ad750fb34ff9697a3223806b3189b5a2a)
- [x] simplified deltas when detail is expanded (ccf61b6ad750fb34ff9697a3223806b3189b5a2a)
- [x] numeric diff in detail view (b142e82548e8a86a9cb1e224880de12e3301c6a7)
- [x] move numeric diff delta label to right side when it goes to 0 (2d4f0db0134ba11686015c44e8968564009964e5)
- [x] only metrics get numeric diff in list view (98b0ca2b)
- [x] use closest previous build time when exact ancestor is not known (2ceebdadbd950968b903707c5b198b0ad9a7c1f5)
- [x] double render preact bug fix (81569a6d9c316a53bef9e94d3d944e47ce5d2532)
- [x] close remaining details table gaps
    - [x] main-thread work items (68dfdac8a50cee79ef8390d670e3be3fbe698c97)
    - [x] enormous network payload items (68dfdac8a50cee79ef8390d670e3be3fbe698c97)
    - [x] fall back to display value when no diff available (0e0df557690e11ee7c9cf13fc7df8c3ffae5b905)
    - [x] link details type (844110ab3a47e616b44fa2912068ed5b72e12097)
- [x] bug fix for different URLs in UI (f7e797eda16ec096c44cce6fc4c2e9bb43e8e009)
- [x] diff logic improvements
    - [x] key by things other than URL (i.e. for budget categories) (5329b6255912b9788d9f367b6bebea1cb79ca725)
    - [x] handle hash components of a URL (dee2613c7cc9bb2dc89f6b9cad4119230011d631)
    - [x] sort within item groups (#31) (2a8d6ad24b504465436c264e710df6b10c26851d)
- [x] limit builds in hash selector (4f5476a4)
- [x] limit statistics fetched for dashboard (4f5476a4)
- [x] fix same branch compare/base (91a4c7a0)
- [x] label only "added"/"removed" and move to before first numeric cell (5bf7b482)
- [x] add percentages everywhere (2f0fb8e52eab3d73500a9b327c03c2fb48154b93)
- [x] smaller font size of upper/lower limits (ead96e7c)
- [x] use ms everywhere for deltas (7c1e5ff6)
- [x] branch picker on project dashboard (ec95bc8a)
- [x] move avatar inside pill (5e3e71e0)
- [x] extend hover color to entire build picker row (4bcaa4eae338b2d0b85e338b90f19e2cb1516466)
- [x] revert back to pill background instead of header (4bcaa4eae338b2d0b85e338b90f19e2cb1516466)
- [x] tweak base/compare pill colors in hash picker (4bcaa4eae338b2d0b85e338b90f19e2cb1516466)
- [x] run through all spec colors/sizes in figma
- [x] consolidation of error states on "no diff" view (be6a26362ef65df4b6e6fb8c83419fd2afe5c4c7)
- [x] legit loading spinner (f22bb8c3c422f07813bf2473532fbb71a8764050)
- [x] faded out base/compare chip hash selector (4bcaa4eae338b2d0b85e338b90f19e2cb1516466)
- [x] optional merge base (#36)
- [x] no diff available fixes for opportunities (c4a2c406cc17bfb25d8d2d823abb6f4a8e86e8a9) (eaffaf2b71270bcd91a93ce25411383cd129508f) (f87124aaf76182fea8973e7b5ef1f712849ba8d6)
- [x] handle image thumbnail failure to load (14666ac6d0b7b26ab29994bd25551c86c3a1c68d)
- [x] favicon (2dc0f90737049dc454ed4ad6279d4bf93c564bf0)
- [x] project pane on scroll isn't full viewport width (0f9ff47a297f008d37db7e6c7e0464bf9f257d6b)
- [x] fix base+compare on same branch (1b4619fded2d49003340a598cdaf762df54dd4c6)
- [x] friendly URLs (696a95ee662129ed2ec9389444b7f95567d98b00)
- [x] synthesize group for best practices audits (4fcf7af78d88a4e15c27a5b51b770a84d9128bb5)

### CLI
- [x] update notifier (7bcd7f20fcc557bf2ec8034be148ebe0acecbc59)
- [x] rename to `staticDistDir` (62441023e67c1a36f71125a7eede1ee208442290)
- [x] `assert` on median build, not just median value (70aef5217d1a42af9debe1413d9e82854e77b3b7)
- [x] `upload` URL replacements for `<port>`, `<uuid>`, etc (ccb528b7a250fa2913415bb0b6a390a4440381aa)
- [x] generate lighthouserc from budgets.json (00cf1a4d9f5ba53004a3b09044f6908636d8b807)
- [x] lighthouserc granular budget assertions (3d29976e778132fb0f2d59f71ee7bde5c61d26f1)
- [x] `assert` allow assertion on multiple urls/patterns as keys in matrix
- [x] update the `lighthouse:recommended` preset (e78b25a62123ba353d870c572345248ceb7fbd11)
- [x] rename `mergeMethod` to `aggregationMethod` (c0329f1e4b280b84c7249a8571af3af3f6339ef8)
- [x] support file-wide default aggregationMethod (6c098cdd52e5e6f394a2fb20a3292a1f48df2d1d)
- [x] collect mode with a server for local files (ebbe030c7a80c7f61d4b9611698246b181bdaaaf)
- [x] automegadoeverything command (5e42e217b823278382785ac752cc3b34e29dd721)
- [x] print audit titles and learn more link (261fd0ae646104a71148fa07ef81858132e84df7)
- [x] `healthcheck` that fails/warns when things aren't configured correctly (#38) 
- [x] list item details on failure

### API

- [x] create friendly slug for project (40de6e7395211f62a435dae25a0ecb1d80553155) (26024ff63d6158cdb8e16d0157b53852de9e91be)
- [x] support partial hash search (e43d0e7c8f46b93db7587bb8164f897758983d9d)
- [x] create migration files for schema changes (d27e181e3b26daf8cd7a017e04331ec61cc0b679)
- [x] route for closest build to target ancestor (e19d9cdbf6c5dc15c101bc66cc46f90dff3e639d)
- [x] use a real token distinct from project ID (4e814d76630c5c5c2995b172a301dbe23c36a91c)
- [x] committedAt (#35)
- [x] add statistic version to statistic records (#4)  (c2dc676ecf2a9c205d78260f9ce69713d4f9dafb) (0f4dd6b64a9d2a138d78887bfb6e5c441f8eda54)

### Tests

- [x] multiple URL comparison test in build view (914dbd712c521a55124ef035042a31514f9b6b79)
- [x] setup LHCI on itself for homepage, project dashboard, build view (13c9bfdfbc7bd4fa66b752d698dc4871dd38e76f)
- [x] setup `assert` flow in dogfood  (0cc017820398a91cfd3d5807ae9c2e895f3d77c7)

### Perf

- [x] spin up a test server of 50 LHRs/build, 1000 builds (n1-standard-1 handled 3700 LHRs with 75 builds easily, only ~2GB sqlite file, ~20ms response times for common queries, 300ms response times for lifecycle/statistic computation)

#### Docs
- [x] document versioning strategy for breaking changes
- [x] document healthcheck and common mistakes (git depth, external contributions preventing githubToken, creating empty commits to rerun, etc)
- [x] document assertion format with basic examples (9e10393d8001a7d6913f830b01ca88c2c2fab338)
- [x] getting started guide (6babedc1fc4322c23a218d523abb6538a7acd776)
- [x] update docs for optionality of fallback server (59434275d70f116101db141c6ad61223fcc1271b)
- [x] docs on automegadoeverything command (59434275d70f116101db141c6ad61223fcc1271b)

### Design Feedback

- [x] ordering of audits (bc476b6fbe9888f55218876ee6c002f49eda0156)

### Misc

- [x] publish docker image with 0.3.0
- [x] update all examples with install of 0.3.x

### UI
- [x] warning when using a different build from exact ancestor (47f968ff314d93271426c3ce35aa378b9f7008e3)
- [x] LH report link next to legend (1188120bfbbf1aaa43220586f9a4377418fa5453)
- [x] minimum diff threshold slider on build view (1188120bfbbf1aaa43220586f9a4377418fa5453)
- [x] clicking off build hash picker closes it (0652474ad9b64a174e0bc70d5599f786e445f0d2)
- [x] redesign of "no diff" view (47f968ff314d93271426c3ce35aa378b9f7008e3)
- [x] new pill design for item deltas
- [ ] recent activity pagination
- [x] git tree visualization on build-view hash picker
- [x] nicer tooltips (#30)
- [x] `--start-server-command` (#37) (#46)
- [x] audit-specific icons (c7934e6785d1eab2fa73125aeba6cbf5c29d3bcd)
- [ ] add color to the gauges when there is no diff at all
- [ ] calibrated/overview metrics
- [ ] dates on hash picker commits
- [x] nicer design of empty states (4d268a71f07b0a10c73e1ca28877e5b6882c9752) (04126b8046527f589bf018bd2afe30237fa9a1d0) (3913e433afac58cf936a909806612c81551f99f7)
- [ ] closeable warning boxes
- [ ] diff logic improvements
    - [ ] extract numbers from displayValue and use those for ignorable thresholds
    - [x] ignore pass -> pass variance (68a906d200c4a5286d98ee656d842368d5e3a9ec)

### API
- [ ] pagination on builds
- [x] GH app and proxy service
  - [x] create the actual GH app/logo/copy/etc
  - [x] route to create a GH token for you
  - [x] route to validate the GH token against the repo and post the status to GH

### CLI
- [x] `upload` target of transient cloud storage service (cbad14dfb5b70893319af4a64e7d05ac16e241cb)
- [x] `upload` sets a GH status check bit (97d263969f6a3e19a7cc9f3d26a16941830afcd8)
- [x] automatically find a local `.lighthouserc` (bd7d44c45ea82e456f13bac46fb5a4d48fa65c13)
- [x] assert against category scores (13c687edbf67ca05094b771da7f84a9b46d13cec)
- [x] `open` command view HTML reports (df13eb4752307c6af2cbe885cfe2cfcb53a89b60)

### Docs

- [x] document travis CI setup for basic assert flow
- [x] document installation of CI server
- [x] document different ways to use `budgets.json` with lighthouse ci

## 🏈 🏖 Punt till after CDS

- [ ] e2e puppeteer UI tests for all mocked design areas
- [ ] serve thumbnails of images from bespoke thumbnails entry in LHR
- [ ] configurable base branch #82 
- [ ] allow last build to be overriden/deleted by a new build
- [ ] embed thumbnails of images that are on localhost into LHR
- [ ] Errored/missing audits #83 
- [ ] List of no diff/hidden audits
- [ ] Project management #86 
- [ ] Authentication/user management #85 
- [ ] bespoke non-platform dropdowns

-------

CDS Feedback

- Docs and CircleCI tests #90 
- Windows tests #67 
- `--puppeteer-script` #89 
- Docs on auth testing
- Docs on jenkins setup #91 
- GitHub enterprise URL configuration #92

**Comment by patrickhulce** [comment]
Separate issues have been filed for efforts that deserve separate tracking, closing as the MVP has shipped! 🎉
